
package ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "StudentWebServiceImplService", targetNamespace = "http://ws/", wsdlLocation = "http://localhost:1986/wss/hello?wsdl")
public class StudentWebServiceImplService
    extends Service
{

    private final static URL STUDENTWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException STUDENTWEBSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName STUDENTWEBSERVICEIMPLSERVICE_QNAME = new QName("http://ws/", "StudentWebServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:1986/wss/hello?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        STUDENTWEBSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        STUDENTWEBSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public StudentWebServiceImplService() {
        super(__getWsdlLocation(), STUDENTWEBSERVICEIMPLSERVICE_QNAME);
    }

    public StudentWebServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), STUDENTWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public StudentWebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, STUDENTWEBSERVICEIMPLSERVICE_QNAME);
    }

    public StudentWebServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, STUDENTWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public StudentWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StudentWebServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns StudentWebService
     */
    @WebEndpoint(name = "StudentWebServiceImplPort")
    public StudentWebService getStudentWebServiceImplPort() {
        return super.getPort(new QName("http://ws/", "StudentWebServiceImplPort"), StudentWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StudentWebService
     */
    @WebEndpoint(name = "StudentWebServiceImplPort")
    public StudentWebService getStudentWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws/", "StudentWebServiceImplPort"), StudentWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (STUDENTWEBSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw STUDENTWEBSERVICEIMPLSERVICE_EXCEPTION;
        }
        return STUDENTWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
